apiVersion: v1
kind: Namespace
metadata:
  name: triton
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  namespace: triton
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
      - name: triton
        image: shopguard/triton-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: grpc
          containerPort: 8001
          protocol: TCP
        - name: metrics
          containerPort: 8002
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
      restartPolicy: Always
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: triton
  namespace: triton
  labels:
    app: triton
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: grpc
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: metrics
    port: 8002
    targetPort: 8002
    protocol: TCP
  selector:
    app: triton